# Generated by Django 5.0.6 on 2024-05-21 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='code')),
                ('value', models.CharField(blank=True, max_length=20, null=True, verbose_name='value')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIMESTAMP', models.DateTimeField(blank=True, help_text='Texto explicativo do campo', null=True, verbose_name='Time Stamp')),
                ('RECORD', models.PositiveIntegerField(blank=True, help_text='Texto explicativo do campo', null=True, unique=True, verbose_name='Record')),
                ('VelVent', models.DecimalField(blank=True, decimal_places=5, help_text='Texto explicativo do campo', max_digits=12, null=True, verbose_name='VelVent ms')),
                ('DirVent', models.DecimalField(blank=True, decimal_places=5, help_text='Texto explicativo do campo', max_digits=12, null=True, verbose_name='DirVent')),
                ('RadW', models.DecimalField(blank=True, decimal_places=5, help_text='Texto explicativo do campo', max_digits=12, null=True, verbose_name='RadW')),
                ('RadFlukJ', models.DecimalField(blank=True, decimal_places=5, help_text='Texto explicativo do campo', max_digits=12, null=True, verbose_name='RadFlukJTot')),
                ('Temp', models.DecimalField(blank=True, decimal_places=5, help_text='Texto explicativo do campo', max_digits=12, null=True, verbose_name='Temp')),
                ('UR', models.DecimalField(blank=True, decimal_places=5, help_text='Texto explicativo do campo', max_digits=12, null=True, verbose_name='UR')),
                ('Press', models.DecimalField(blank=True, decimal_places=5, help_text='Texto explicativo do campo', max_digits=12, null=True, verbose_name='Press_mbar')),
                ('Chuva', models.DecimalField(blank=True, decimal_places=5, help_text='Texto explicativo do campo', max_digits=12, null=True, verbose_name='Chuva_mm_Tot')),
                ('Chuva_UOM', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chuva_UOM', to='data.basedata')),
                ('DirVent_UOM', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DirVent_UOM', to='data.basedata')),
                ('Press_UOM', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Press_UOM', to='data.basedata')),
                ('RadFlukJ_UOM', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RadFlukJ_UOM', to='data.basedata')),
                ('RadW_UOM', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RadW_UOM', to='data.basedata')),
                ('Temp_UOM', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Temp_UOM', to='data.basedata')),
                ('UR_UOM', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UR_UOM', to='data.basedata')),
                ('VelVent_UOM', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VelVent_UOM', to='data.basedata')),
            ],
        ),
    ]
