# Generated by Django 5.0.6 on 2024-05-20 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climatedata',
            name='Chuva_UOM',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='DirVent_UOM',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='Press_UOM',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='RadFlukJ_UOM',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='RadW_UOM',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='Temp_UOM',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='UR_UOM',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='VelVent_UOM',
        ),
    ]
