# Generated by Django 5.0.6 on 2024-05-20 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_climatedata_chuva_uom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climatedata',
            name='RECORD',
        ),
    ]
