# Generated by Django 5.0.6 on 2024-05-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_climatedata_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatedata',
            name='RECORD',
            field=models.PositiveIntegerField(blank=True, help_text='Texto explicativo do campo', null=True, unique=True, verbose_name='Record'),
        ),
    ]
