# Generated by Django 5.0.6 on 2024-07-13 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseData',
            fields=[
                ('id_base_data', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id_climate_data', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('record', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('wind_direction', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('RadW', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('RadFlukJ', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('degrees', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('ur', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('rain_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
            ],
        ),
    ]
